"""Initial v.

Revision ID: 961a6a30f301
Revises: dead0ab75eff
Create Date: 2024-04-03 16:06:32.828652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961a6a30f301'
down_revision = 'dead0ab75eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_the_book_back', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('transaction_book', schema=None) as batch_op:
        batch_op.drop_column('is_the_book_back')

    # ### end Alembic commands ###
