"""last

Revision ID: dead0ab75eff
Revises: 
Create Date: 2024-03-26 16:19:51.883111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dead0ab75eff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_writer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_books', sa.Integer(), nullable=True),
    sa.Column('id_writer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_books'], ['books.id'], ),
    sa.ForeignKeyConstraint(['id_writer'], ['writer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_writer')
    # ### end Alembic commands ###
